### ISSUE TITLE
Make Readme in proper format

### ISSUE THREAD

**Issue by rishabh-jain424** [rishabh-jain424/Longclaw#1]

**Comment by Vineet-Dhaimodker** [comment]
I would like to take up this issue. Please assign it to me @rishabh-jain424 .

**Comment by rishabh-jain424** [comment]
@Vineet-Dhaimodker thanks for coming forward to take up this issue. 
Actually, I have to make it update as soon as possible so, I update it.

But if you know Python language, Can you try to add new functionality or to make the code optimize.
